obstacle_range: 5.5
raytrace_range: 4.5

footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
#robot_radius: 0.17

inflation_radius: 0.8
cost_scaling_factor: 3.0

map_type: costmap
observation_sources: scan
scan: {sensor_frame: base_scan, data_type: LaserScan, topic: laser/scan, marking: true, clearing: true}
